# Metrics
Faithfulness:
    Faithfulness Correlation:
    Faithfulness Estimate:
    Pixel-Flipping:
    Region Segmentation:
    Monotonicity-Arya:
    Monotonicity-Nguyen:
    Selectivity:
    SensitivityN:
    IROF:
    ROAD:
    Infidelity:
    Sufficiency:

Robustness:
    Continuity Test:
    Local Lipschitz Estimate:
    Max-Sensitivity:
    Avg-Sensitivity:
    Consistency:
    Relative Input Stability:
    Relative Output Stability:
    Relative Representation Stability:

Localisation:
    Pointing Game:
    Top-K Intersection:
    Relevance Mass Accuracy:
    Relevance Rank Accuracy:
    Attribution Localisation :
    Focus:

Complexity:
    Sparseness:
    Complexity:
    Effective Complexity:

Randomisation:
    MPRT:
    Smooth MPRT:
    Efficient MPRT:
    Random Logit:

Axiomatic:
    Completeness:
    NonSensitivity:
    InputInvariance:
