# Metrics
faithfulness:
  faithfulness_corr:
  faithfulness_estimate:
  monotonicity:
  monotonicity_correlation:
  pixel_flipping:
  region_perturb:
  selectivity:
  sensitivity_n:
  irof:
  infidelity:
  road:
  sufficiency:

robustness:
  local_lipschitz_estimate:
  max_sensitivity:
  average_sensitivity:
  continuity:
  consistency:
  relative_input_stability:
  relative_output_stability:
  relative_representation_stability:

#localization:
#  pointing_game:
#  attribution_localisation:
#  top_k_intersection:
#  relevance_rank_accuracy:
#  relevance_mass_accuracy:
#  auc:

randomization:
  model_parameter_randomisation:
  random_logits:

complexity:
  sparseness:
  complexity:
  effective_complexity:

axiomatic:
  completeness:
  non_sensitivity:
  # input_invariance: # this one is difficult to implement as quantus implementation is not made for wrapper models