# Metrics

Faithfulness:
    IROF:
    Selectivity:
    Region Segmentation MORF:
    Region Segmentation LERF:

Robustness:
    Max-Sensitivity:
    Relative Input Stability:
    Relative Output Stability:

Randomisation:
    Random Logit:

Complexity:
    Sparseness:
    Effective Complexity:
