# Metrics
faithfulness:
  region_perturb:
  selectivity:
  infidelity:

robustness:
  relative_input_stability:
  relative_output_stability:

complexity:
  sparseness:
  complexity:
  effective_complexity:

randomization:
   # model_parameter_randomisation:
   random_logits:


axiomatic:
  completeness:
  non_sensitivity:
