# Metrics

Faithfulness:
    Region Segmentation:
    Selectivity:
    Infidelity:

Robustness:
    Max-Sensitivity:
    Relative Input Stability:
    Relative Output Stability:

Randomisation:
    Random Logit:

Localisation:
    Pointing Game:
    Top-K Intersection:
    Relevance Mass Accuracy:
    Relevance Rank Accuracy:
    Attribution Localisation:
    AUC:

Complexity:
    Sparseness:
    Effective Complexity:

