# Metrics
#faithfulness:
#  region_perturb:
#  selectivity:
#  infidelity:
#
#robustness:
#  relative_input_stability:
#  relative_output_stability:
#
#randomization:
#  random_logits:
#
#complexity:
#  sparseness:
#  complexity:
#  effective_complexity:
#
#axiomatic:
#  completeness:
#  non_sensitivity:

localization:
  pointing_game:
  attribution_localisation:
  top_k_intersection:
  relevance_rank_accuracy:
  relevance_mass_accuracy:
  auc: