# Metrics

Faithfulness:
    Region Segmentation:
    Selectivity:
    Infidelity:

Robustness:
    Max-Sensitivity:
    Relative Input Stability:
    Relative Output Stability:

Randomisation:
    Random Logit:

Complexity:
    Sparseness:
    Effective Complexity:

Axiomatic:
    Completeness:
    NonSensitivity:

Localisation:
    Pointing Game:
    Top-K Intersection:
    Relevance Mass Accuracy:
    Relevance Rank Accuracy:
    Attribution Localisation :
    AUC:
