---
# Description: General configuration file for the project

# General parameters
model_name: 'vgg'
dataset_name: 'ben'
num_classes: 19
input_channels: 14

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'deeplift'
  - 'guided_gradcam'
  - 'occlusion'
  - 'gradcam'

# Dataset parameters
data:
    images_lmdb_path: "/media/storagecube/jonasklotz/BigEarthNet-V2/BENv2.lmdb"
    labels_path: "/media/storagecube/jonasklotz/BigEarthNet-V2/lbls.parquet"
    train_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/lithuania_train.csv"
    val_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/lithuania_val.csv"
    test_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/lithuania_test.csv"
    s2s1_mapping_file: "/media/storagecube/jonasklotz/BigEarthNet-V2/new_s2s1_mapping.parquet"

    batch_size: 32 #128
    num_workers: 8 # 8
    pin_memory: False
    force_shuffle: False # shuffle also test loader


# Training parameters
max_epochs: 20
learning_rate: 0.025
threshold: 0.5
momentum: 0.9


# whether to load the batches from a specific path
zarr_path: '/home/jonasklotz/Studys/MASTERS/results_22_4_final/ben/ben_explanations/ben_vgg_2024-04-20_15-48-28.zarr'
model_path: 'models_final/ben_vgg/early_stopped.ckpt'

