---
# Description: General configuration file for the project

# General parameters
model_name: 'vgg'
dataset_name: 'deepglobe'
num_classes: 6
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'gradcam'
  - 'deeplift'

# Dataset parameters
data:
  images_lmdb_path: "/media/storagecube/jonasklotz/BigEarthNet-V2/BENv2.lmdb"
  labels_path: "/media/storagecube/jonasklotz/BigEarthNet-V2/lbls.parquet"
  train_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/all_train.csv"
  val_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/all_val.csv"
  test_csv: "/media/storagecube/jonasklotz/BigEarthNet-V2/benv2_splits/all_test.csv"
  segmentations_lmdb_path: None # "/media/storagecube/jonasklotz/BigEarthNet-V2/"

  batch_size: 16 #128
  num_workers: 0 # 8
  pin_memory: True
  force_shuffle: True # shuffle also test loader only for metrics evaluation


# Training parameters
max_epochs: 50
learning_rate: 0.05
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5


# whether to load the batches from a specific path
zarr_path: 'results/deepglobe_vgg_final.zarr'
model_path: 'models/deepglobe_vgg_final/final_model.pt'



