---
# Description: General configuration file for the project
visualize: False

# General parameters
model_name: 'vgg'
dataset_name: 'caltech101'
num_classes: 101
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'deeplift'
  - 'guided_gradcam'
  - 'occlusion'
  - 'gradcam'

# Dataset parameters
data:
  batch_size: 32
  num_workers: 8
  pin_memory: False


# Training parameters
max_epochs: 10
learning_rate: 0.025
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5

# whether to load the batches from a specific path
zarr_path: '/home/jonasklotz/Studys/MASTERS/results_22_4_final/caltech/explanations/caltech101_vgg.zarr'
model_path: 'models_final/caltech101_vgg_final/final_model.pt'



