---
# Description: General configuration file for the project
visualize: False

# General parameters
model_name: 'resnet'
layer_number: 34 # 18 34 50
dataset_name: 'caltech101'
num_classes: 101
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'gradcam'
  - 'deeplift'

# Dataset parameters
data:
  batch_size: 4
  num_workers: 4
  pin_memory: True

# Training parameters
max_epochs: 50
learning_rate: 0.01
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5

# whether to vectorize the explanation generation
vectorize: False

# whether to load the batches from a specific path
zarr_path: '/home/jonasklotz/Studys/MASTERS/XAI/results/explanations_2024-01-20_16-29-46.zarr' # If this is empty the most recent will be loaded "/home/jonasklotz/Studys/MASTERS/XAI/results/new_batches"

model_path: 'models/caltech101_resnet_2024-01-30_12-19-49/epochs_50.pt'



