---
# Description: General configuration file for the project

# General parameters
model_name: 'vgg'
dataset_name: 'deepglobe'
num_classes: 6
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'gradcam'
  - 'deeplift'

# Dataset parameters
data:
  images_lmdb_path: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/patches.lmdb"
  labels_path: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/labels.parquet"
  train_csv: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_train.csv"
  val_csv: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_val.csv"
  test_csv: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_test.csv"
  segmentations_lmdb_path: "/media/storagecube/data/datasets/deepGlobe/ML_DeepGlobe/segmentations.lmdb"

  batch_size: 128 #128
  num_workers: 8 # 8
  pin_memory: True
  force_shuffle: True # shuffle also test loader only for metrics evaluation


# Training parameters
max_epochs: 50
learning_rate: 0.05
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5


# whether to load the batches from a specific path
zarr_path: 'results/metrics/deepglobe_vgg_good/deepglobe_vgg_2024-02-13_12-45-28.zarr'#"results/deepglobe_vgg_2024-02-20_16-38-35.zarr"#'results/metrics/deepglobe_vgg_good/deepglobe_vgg_2024-02-13_12-45-28.zarr'
model_path: 'models/deepglobe_vgg_final/final_model.pt'



