---
# Description: General configuration file for the project

# General parameters
model_name: 'vgg'
dataset_name: 'deepglobe'
num_classes: 6
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'deeplift'
  - 'guided_gradcam'
  - 'occlusion'
  - 'gradcam'

# Dataset parameters
data:
    images_lmdb_path: "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/patches.lmdb"
    labels_path: "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/labels.parquet"
    train_csv: "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_train.csv"
    val_csv: "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_val.csv"
    test_csv: "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/splits/deepglobe_version2_test.csv"
    segmentations_lmdb_path: '/media/storagecube/jonasklotz/deepglobe_vgg_lmdbs/deeplift.lmdb'
# "/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/segmentations.lmdb"##


    batch_size: 32 #128
    num_workers: 8 # 8
    pin_memory: False
    force_shuffle: False # shuffle also test loader


# Training parameters
max_epochs: 20
learning_rate: 0.025
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5


# whether to load the batches from a specific path
zarr_path: '/home/jonasklotz/Studys/MASTERS/XAI/results/metrics/deepglobe_vgg_good/deepglobe_vgg_2024-02-13_12-45-28.zarr'
#"results/deepglobe_vgg_2024-02-20_16-38-35.zarr"#'results/metrics/deepglobe_vgg_good/deepglobe_vgg_2024-02-13_12-45-28.zarr'
model_path: 'models/deepglobe_vgg_20EP/final_model.ckpt'



