---
# Description: General configuration file for the project
training: False
explanations: True
evaluations: False
visualize: False

# General parameters
model_name: 'resnet'
layer_number: 18
dataset_name: 'deepglobe'
num_classes: 6
input_channels: 3

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  #- 'integrated_gradients'
  #- 'gradcam'
  #- 'deeplift'

# Dataset parameters
data:
  images_lmdb_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/patches.lmdb"
  labels_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/labels.parquet"
  train_csv: "/media/storagecube/jonasklotz/deepGlobe/splits/deepglobe_version1_train.csv"
  test_csv: "/media/storagecube/jonasklotz/deepGlobe/splits/deepglobe_version1_test.csv"
  segmentations_lmdb_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/segmentations.lmdb"
  batch_size: 32
  num_workers: 10
  pin_memory: True

# Training parameters
max_epochs: 10
learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5





