---
# Description: General configuration file for the project
visualize: False

# General parameters
model_name: 'resnet'
layer_number: 18
dataset_name: 'deepglobe'
num_classes: 6
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'gradcam'
  - 'deeplift'

# Dataset parameters
data:
  images_lmdb_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/patches.lmdb"
  labels_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/labels.parquet"
  train_csv: "/home/jonas/splits/deepglobe_version2_train.csv"
  val_csv: "/home/jonas/splits/deepglobe_version2_val.csv"
  test_csv: "/home/jonas/splits/deepglobe_version2_test.csv"
  segmentations_lmdb_path: "/media/storagecube/jonasklotz/deepGlobe/ML_DeepGlobe/segmentations.lmdb"

  batch_size: 32
  num_workers: 0
  pin_memory: True

# Training parameters
max_epochs: 50
learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5

# whether to vectorize the explanation generation
vectorize: False

# whether to load the batches from a specific path
zarr_path: '/home/jonasklotz/Studys/MASTERS/XAI/results/explanations_2024-01-08_13-56-34.zarr' # If this is empty the most recent will be loaded "/home/jonasklotz/Studys/MASTERS/XAI/results/new_batches"


loss_name: 'BCEWithLogitsLoss'
loss_explanation: 'deeplift'





