faithfulness_corr:
faithfulness_estimate:
monotonicity:
monotonicity_correlation:
pixel_flipping:
region_perturb:
selectivity:
sensitivity_n:
irof:
infidelity:
road:
sufficiency:
local_lipschitz_estimate:
max_sensitivity:
average_sensitivity:
continuity:
consistency:
relative_input_stability:
relative_output_stability:
relative_representation_stability:
pointing_game:
attribution_localisation:
top_k_intersection:
relevance_rank_accuracy:
relevance_mass_accuracy:
auc:
sparseness:
complexity:
effective_complexity:
model_parameter_randomisation:
random_logits:
completeness:
non_sensitivity:
input_invariance: