---
# Description: General configuration file for the project
visualize: False

# General parameters
model_name: 'vgg'
layer_number: 34 # 18 34 50
dataset_name: 'caltech101'
num_classes: 101
input_channels: 3

pretrained: False

# Explanation parameters
explanation_methods:
  - 'lime'
  - 'lrp'
  - 'integrated_gradients'
  - 'gradcam'
  - 'deeplift'

# Dataset parameters
data:
  batch_size: 8 # optimal training: 128
  num_workers: 0
  pin_memory: False
  force_shuffle: True # shuffle also test loader


# Training parameters
max_epochs: 50
learning_rate: 0.05
momentum: 0.9
weight_decay: 0.0005
optimizer: 'sgd'
scheduler: 'step'
threshold: 0.5

loss: "rrr"
rrr_explanation: "deeplift"
rrr_lambda: 1

# whether to load the batches from a specific path
zarr_path: 'results/caltech101_vgg_final.zarr'
model_path: 'models/caltech101_vgg_final/final_model.pt'



